{
	"classMsg":{ 
		"clientList":"com.gzwanhong.domain.Client"
	},
	"startRow":1,
	"emptyClass":{
		"clientList":0
	},
	"columnMsg":[ 
	    {
	    	"columnName":"name",
	    	"objectName":"clientList",
	    	"columnIndex":0,
	    	"methodName":"setName",
	    	"argClass":"java.lang.String"
	    },
	    {
	    	"columnName":"linkman",
	    	"objectName":"clientList",
	    	"columnIndex":1,
	    	"isComment":true,
	    	"methodName":"setLinkman",
	    	"argClass":"java.lang.String"
	    },
	    {
	    	"columnName":"field1",
	    	"objectName":"clientList",
	    	"columnIndex":2,
	    	"methodName":"setField1",
	    	"argClass":"java.lang.String"
	    },
	    {
	    	"columnName":"project",
	    	"objectName":"clientList",
	    	"columnIndex":4,
	    	"methodName":"setProject",
	    	"argClass":"java.lang.String",
	    	"valMap":{     
	    		"ISO9000":"ISO9000",
	    		"ISO14000":"ISO14000",
	    		"OHSAS18000":"OHSAS18000",
	    		"ISO20000":"ISO20000",
	    		"ISO27001":"ISO27001",
	    		"其它体系认证":"其它体系认证",
	    		"CE":"CE",
	    		"建筑施工资质":"建筑施工资质",
	    		"建筑设计资质":"建筑设计资质",
	    		"系统集成资质":"系统集成资质",
	    		"安防资质":"安防资质",
	    		"运维资质":"运维资质"
	    	}
	    },
	    {
	    	"columnName":"remark",
	    	"objectName":"clientList",
	    	"columnIndex":5,
	    	"methodName":"setRemark",
	    	"argClass":"java.lang.String"
	    }
	]
}