
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.gzwanhong.webserviceClient;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-07-31T21:30:14.279+08:00
 * Generated source version: 3.1.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "serviceInterface",
                      portName = "serviceInterfacePort",
                      targetNamespace = "http://webservice.gzwanhong.com",
                      wsdlLocation = "http://127.0.0.1:8080/synFile/service/serviceInterface?wsdl",
                      endpointInterface = "com.gzwanhong.webserviceClient.ServiceInterface")
                      
public class ServiceInterfacePortImpl implements ServiceInterface {

    private static final Logger LOG = Logger.getLogger(ServiceInterfacePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.gzwanhong.webserviceClient.ServiceInterface#testMethod(java.lang.String json)*
     */
    public java.lang.String testMethod(java.lang.String json) throws Exception_Exception   { 
        LOG.info("Executing operation testMethod");
        System.out.println(json);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see com.gzwanhong.webserviceClient.ServiceInterface#getBackupFile(java.lang.String json)*
     */
    public java.lang.String getBackupFile(java.lang.String json) throws Exception_Exception   { 
        LOG.info("Executing operation getBackupFile");
        System.out.println(json);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see com.gzwanhong.webserviceClient.ServiceInterface#addRecord(java.lang.String json)*
     */
    public java.lang.String addRecord(java.lang.String json) throws Exception_Exception   { 
        LOG.info("Executing operation addRecord");
        System.out.println(json);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see com.gzwanhong.webserviceClient.ServiceInterface#startCheckFile(java.lang.String json)*
     */
    public java.lang.String startCheckFile(java.lang.String json) throws Exception_Exception   { 
        LOG.info("Executing operation startCheckFile");
        System.out.println(json);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see com.gzwanhong.webserviceClient.ServiceInterface#getAllFile(java.lang.String json)*
     */
    public java.lang.String getAllFile(java.lang.String json) throws Exception_Exception   { 
        LOG.info("Executing operation getAllFile");
        System.out.println(json);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

    /* (non-Javadoc)
     * @see com.gzwanhong.webserviceClient.ServiceInterface#downloadFile(java.lang.String json)*
     */
    public java.lang.String downloadFile(java.lang.String json) throws Exception_Exception   { 
        LOG.info("Executing operation downloadFile");
        System.out.println(json);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new Exception_Exception("Exception...");
    }

}
