
package com.gzwanhong.webserviceClient;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-07-31T21:30:14.292+08:00
 * Generated source version: 3.1.7
 * 
 */
 
public class ServiceInterface_ServiceInterfacePort_Server{

    protected ServiceInterface_ServiceInterfacePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ServiceInterfacePortImpl();
        String address = "http://127.0.0.1:8080/synFile/service/serviceInterface";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ServiceInterface_ServiceInterfacePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
