
package com.gzwanhong.webserviceClient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-07-31T21:30:14.258+08:00
 * Generated source version: 3.1.7
 * 
 */
public final class ServiceInterface_ServiceInterfacePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.gzwanhong.com", "serviceInterface");

    private ServiceInterface_ServiceInterfacePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServiceInterface_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServiceInterface_Service ss = new ServiceInterface_Service(wsdlURL, SERVICE_NAME);
        ServiceInterface port = ss.getServiceInterfacePort();  
        
        {
        System.out.println("Invoking testMethod...");
        java.lang.String _testMethod_json = "";
        try {
            java.lang.String _testMethod__return = port.testMethod(_testMethod_json);
            System.out.println("testMethod.result=" + _testMethod__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getBackupFile...");
        java.lang.String _getBackupFile_json = "";
        try {
            java.lang.String _getBackupFile__return = port.getBackupFile(_getBackupFile_json);
            System.out.println("getBackupFile.result=" + _getBackupFile__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addRecord...");
        java.lang.String _addRecord_json = "";
        try {
            java.lang.String _addRecord__return = port.addRecord(_addRecord_json);
            System.out.println("addRecord.result=" + _addRecord__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking startCheckFile...");
        java.lang.String _startCheckFile_json = "";
        try {
            java.lang.String _startCheckFile__return = port.startCheckFile(_startCheckFile_json);
            System.out.println("startCheckFile.result=" + _startCheckFile__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllFile...");
        java.lang.String _getAllFile_json = "";
        try {
            java.lang.String _getAllFile__return = port.getAllFile(_getAllFile_json);
            System.out.println("getAllFile.result=" + _getAllFile__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking downloadFile...");
        java.lang.String _downloadFile_json = "";
        try {
            java.lang.String _downloadFile__return = port.downloadFile(_downloadFile_json);
            System.out.println("downloadFile.result=" + _downloadFile__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
