package com.gzwanhong.webserviceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-07-31T21:30:14.287+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://webservice.gzwanhong.com", name = "serviceInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceInterface {

    @WebMethod(action = "testMethod")
    @RequestWrapper(localName = "testMethod", targetNamespace = "http://webservice.gzwanhong.com", className = "com.gzwanhong.webserviceClient.TestMethod")
    @ResponseWrapper(localName = "testMethodResponse", targetNamespace = "http://webservice.gzwanhong.com", className = "com.gzwanhong.webserviceClient.TestMethodResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String testMethod(
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws Exception_Exception;

    @WebMethod(action = "getBackupFile")
    @RequestWrapper(localName = "getBackupFile", targetNamespace = "http://webservice.gzwanhong.com", className = "com.gzwanhong.webserviceClient.GetBackupFile")
    @ResponseWrapper(localName = "getBackupFileResponse", targetNamespace = "http://webservice.gzwanhong.com", className = "com.gzwanhong.webserviceClient.GetBackupFileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getBackupFile(
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws Exception_Exception;

    @WebMethod(action = "addRecord")
    @RequestWrapper(localName = "addRecord", targetNamespace = "http://webservice.gzwanhong.com", className = "com.gzwanhong.webserviceClient.AddRecord")
    @ResponseWrapper(localName = "addRecordResponse", targetNamespace = "http://webservice.gzwanhong.com", className = "com.gzwanhong.webserviceClient.AddRecordResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String addRecord(
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws Exception_Exception;

    @WebMethod(action = "startCheckFile")
    @RequestWrapper(localName = "startCheckFile", targetNamespace = "http://webservice.gzwanhong.com", className = "com.gzwanhong.webserviceClient.StartCheckFile")
    @ResponseWrapper(localName = "startCheckFileResponse", targetNamespace = "http://webservice.gzwanhong.com", className = "com.gzwanhong.webserviceClient.StartCheckFileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String startCheckFile(
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws Exception_Exception;

    @WebMethod(action = "getAllFile")
    @RequestWrapper(localName = "getAllFile", targetNamespace = "http://webservice.gzwanhong.com", className = "com.gzwanhong.webserviceClient.GetAllFile")
    @ResponseWrapper(localName = "getAllFileResponse", targetNamespace = "http://webservice.gzwanhong.com", className = "com.gzwanhong.webserviceClient.GetAllFileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getAllFile(
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws Exception_Exception;

    @WebMethod(action = "downloadFile")
    @RequestWrapper(localName = "downloadFile", targetNamespace = "http://webservice.gzwanhong.com", className = "com.gzwanhong.webserviceClient.DownloadFile")
    @ResponseWrapper(localName = "downloadFileResponse", targetNamespace = "http://webservice.gzwanhong.com", className = "com.gzwanhong.webserviceClient.DownloadFileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String downloadFile(
        @WebParam(name = "json", targetNamespace = "")
        java.lang.String json
    ) throws Exception_Exception;
}
